classDiagram
    ViewConsole --> UserDao
    UserDao --> User
    User --> Errors

    class ViewConsole {
        +String username
        +getUsernameBy(username: String): User
        +InfoUser(user: User): void
        +InfoError(error: Errors): void
    }

    class UserDao {
        +getUsernameBy(username: String): User
    }

    class User {
        +int id
        +String username
        +String password
        +String email
    }

    class Errors {
        +int code
        +String description
    }
