sequenceDiagram
    participant A as Usuario
    participant B as App
    participant C as WebServer
    participant D as BBDD
    B->>C: Petición de login
    C->>D: Verificar Credenciales
    C->>B: Login OK
    D->>C: Login Ok
    Usuario->>App: Ingresar a la app
    App->>B: Login Ok

