classDiagram
    Vista --> DAOUser
    Vista --> DAOTap
    Vista --> DAOChild
    DAOUser --> User
    DAOTap --> Tap
    DAOChild --> Child
    
    class Vista {
        +ShowUserInfo(User)
        +ShowTapInfo(Tap)
        +ShowChildInfo(Child)
    }
    
    class DAOUser {
        +IdUser(Number)
        +GetUserById(Number)
        +GetAllUser(String)
    }

    class DAOTap {
        +IdTap(Number)
        +GetTapById(Number)
        +GetAllTaps(String)
    }
    
    class DAOChild {
        +IdChild(Number)
        +GetChildById(Number)
        +GetAllChildren(String)
    }
    
    class User {
        -id
        -name
        -sudname
        -email
        +GetName(String)
        +GetSudname(String)
        +GetEmail(String)
    }
    
    class Tap {
        -id
        -status
        +GetStatus(String)
    }
    
    class Child {
        -id
        -name
        -age
        +GetName(String)
        +GetAge(Number)
    }
